// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagment;

public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();

  /**
   * <code>string stockType = 2;</code>
   */
  java.lang.String getStockType();
  /**
   * <code>string stockType = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockTypeBytes();
}
