// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

/**
 * Protobuf type {@code AGVDiagRequest}
 */
public  final class AGVDiagRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AGVDiagRequest)
    AGVDiagRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AGVDiagRequest.newBuilder() to construct.
  private AGVDiagRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AGVDiagRequest() {
    aGVdiagRequest_ = "";
    aGVfrequency_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AGVDiagRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aGVdiagRequest_ = s;
            break;
          }
          case 16: {

            aGVfrequency_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVDiagRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVDiagRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.class, ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.Builder.class);
  }

  public static final int AGVDIAGREQUEST_FIELD_NUMBER = 1;
  private volatile java.lang.Object aGVdiagRequest_;
  /**
   * <code>string AGVdiagRequest = 1;</code>
   */
  public java.lang.String getAGVdiagRequest() {
    java.lang.Object ref = aGVdiagRequest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aGVdiagRequest_ = s;
      return s;
    }
  }
  /**
   * <code>string AGVdiagRequest = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAGVdiagRequestBytes() {
    java.lang.Object ref = aGVdiagRequest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aGVdiagRequest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGVFREQUENCY_FIELD_NUMBER = 2;
  private int aGVfrequency_;
  /**
   * <code>int32 AGVfrequency = 2;</code>
   */
  public int getAGVfrequency() {
    return aGVfrequency_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAGVdiagRequestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aGVdiagRequest_);
    }
    if (aGVfrequency_ != 0) {
      output.writeInt32(2, aGVfrequency_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAGVdiagRequestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aGVdiagRequest_);
    }
    if (aGVfrequency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, aGVfrequency_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartwarehouse.project.AGVSystem.AGVDiagRequest)) {
      return super.equals(obj);
    }
    ds.smartwarehouse.project.AGVSystem.AGVDiagRequest other = (ds.smartwarehouse.project.AGVSystem.AGVDiagRequest) obj;

    boolean result = true;
    result = result && getAGVdiagRequest()
        .equals(other.getAGVdiagRequest());
    result = result && (getAGVfrequency()
        == other.getAGVfrequency());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGVDIAGREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getAGVdiagRequest().hashCode();
    hash = (37 * hash) + AGVFREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + getAGVfrequency();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartwarehouse.project.AGVSystem.AGVDiagRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AGVDiagRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AGVDiagRequest)
      ds.smartwarehouse.project.AGVSystem.AGVDiagRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVDiagRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVDiagRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.class, ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.Builder.class);
    }

    // Construct using ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aGVdiagRequest_ = "";

      aGVfrequency_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVDiagRequest_descriptor;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVDiagRequest getDefaultInstanceForType() {
      return ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVDiagRequest build() {
      ds.smartwarehouse.project.AGVSystem.AGVDiagRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVDiagRequest buildPartial() {
      ds.smartwarehouse.project.AGVSystem.AGVDiagRequest result = new ds.smartwarehouse.project.AGVSystem.AGVDiagRequest(this);
      result.aGVdiagRequest_ = aGVdiagRequest_;
      result.aGVfrequency_ = aGVfrequency_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartwarehouse.project.AGVSystem.AGVDiagRequest) {
        return mergeFrom((ds.smartwarehouse.project.AGVSystem.AGVDiagRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartwarehouse.project.AGVSystem.AGVDiagRequest other) {
      if (other == ds.smartwarehouse.project.AGVSystem.AGVDiagRequest.getDefaultInstance()) return this;
      if (!other.getAGVdiagRequest().isEmpty()) {
        aGVdiagRequest_ = other.aGVdiagRequest_;
        onChanged();
      }
      if (other.getAGVfrequency() != 0) {
        setAGVfrequency(other.getAGVfrequency());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartwarehouse.project.AGVSystem.AGVDiagRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartwarehouse.project.AGVSystem.AGVDiagRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aGVdiagRequest_ = "";
    /**
     * <code>string AGVdiagRequest = 1;</code>
     */
    public java.lang.String getAGVdiagRequest() {
      java.lang.Object ref = aGVdiagRequest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aGVdiagRequest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string AGVdiagRequest = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAGVdiagRequestBytes() {
      java.lang.Object ref = aGVdiagRequest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aGVdiagRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AGVdiagRequest = 1;</code>
     */
    public Builder setAGVdiagRequest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aGVdiagRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AGVdiagRequest = 1;</code>
     */
    public Builder clearAGVdiagRequest() {
      
      aGVdiagRequest_ = getDefaultInstance().getAGVdiagRequest();
      onChanged();
      return this;
    }
    /**
     * <code>string AGVdiagRequest = 1;</code>
     */
    public Builder setAGVdiagRequestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aGVdiagRequest_ = value;
      onChanged();
      return this;
    }

    private int aGVfrequency_ ;
    /**
     * <code>int32 AGVfrequency = 2;</code>
     */
    public int getAGVfrequency() {
      return aGVfrequency_;
    }
    /**
     * <code>int32 AGVfrequency = 2;</code>
     */
    public Builder setAGVfrequency(int value) {
      
      aGVfrequency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AGVfrequency = 2;</code>
     */
    public Builder clearAGVfrequency() {
      
      aGVfrequency_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AGVDiagRequest)
  }

  // @@protoc_insertion_point(class_scope:AGVDiagRequest)
  private static final ds.smartwarehouse.project.AGVSystem.AGVDiagRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartwarehouse.project.AGVSystem.AGVDiagRequest();
  }

  public static ds.smartwarehouse.project.AGVSystem.AGVDiagRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AGVDiagRequest>
      PARSER = new com.google.protobuf.AbstractParser<AGVDiagRequest>() {
    @java.lang.Override
    public AGVDiagRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AGVDiagRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AGVDiagRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AGVDiagRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartwarehouse.project.AGVSystem.AGVDiagRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

