// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface AGVDiagResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AGVDiagResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVdiagType = 1;</code>
   */
  java.lang.String getAGVdiagType();
  /**
   * <code>string AGVdiagType = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVdiagTypeBytes();

  /**
   * <code>int32 systemPerformance = 2;</code>
   */
  int getSystemPerformance();
}
