// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface AGVDiagRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AGVDiagRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVdiagRequest = 1;</code>
   */
  java.lang.String getAGVdiagRequest();
  /**
   * <code>string AGVdiagRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVdiagRequestBytes();
}
