// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

/**
 * Protobuf type {@code AGVProductivityResponse}
 */
public  final class AGVProductivityResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AGVProductivityResponse)
    AGVProductivityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AGVProductivityResponse.newBuilder() to construct.
  private AGVProductivityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AGVProductivityResponse() {
    aGVreportReply_ = "";
    stock_ = "";
    performance_ = "";
    maintenance_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AGVProductivityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aGVreportReply_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stock_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            performance_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            maintenance_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVProductivityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVProductivityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.class, ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.Builder.class);
  }

  public static final int AGVREPORTREPLY_FIELD_NUMBER = 1;
  private volatile java.lang.Object aGVreportReply_;
  /**
   * <pre>
   *Report Response
   * </pre>
   *
   * <code>string AGVreportReply = 1;</code>
   */
  public java.lang.String getAGVreportReply() {
    java.lang.Object ref = aGVreportReply_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aGVreportReply_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Report Response
   * </pre>
   *
   * <code>string AGVreportReply = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAGVreportReplyBytes() {
    java.lang.Object ref = aGVreportReply_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aGVreportReply_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCK_FIELD_NUMBER = 2;
  private volatile java.lang.Object stock_;
  /**
   * <pre>
   *stock track
   * </pre>
   *
   * <code>string stock = 2;</code>
   */
  public java.lang.String getStock() {
    java.lang.Object ref = stock_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stock_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *stock track
   * </pre>
   *
   * <code>string stock = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStockBytes() {
    java.lang.Object ref = stock_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stock_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERFORMANCE_FIELD_NUMBER = 3;
  private volatile java.lang.Object performance_;
  /**
   * <pre>
   *performance of AGVs
   * </pre>
   *
   * <code>string performance = 3;</code>
   */
  public java.lang.String getPerformance() {
    java.lang.Object ref = performance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      performance_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *performance of AGVs
   * </pre>
   *
   * <code>string performance = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPerformanceBytes() {
    java.lang.Object ref = performance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      performance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAINTENANCE_FIELD_NUMBER = 4;
  private volatile java.lang.Object maintenance_;
  /**
   * <pre>
   *maintenance of AGVs
   * </pre>
   *
   * <code>string maintenance = 4;</code>
   */
  public java.lang.String getMaintenance() {
    java.lang.Object ref = maintenance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      maintenance_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *maintenance of AGVs
   * </pre>
   *
   * <code>string maintenance = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMaintenanceBytes() {
    java.lang.Object ref = maintenance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      maintenance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAGVreportReplyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aGVreportReply_);
    }
    if (!getStockBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stock_);
    }
    if (!getPerformanceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, performance_);
    }
    if (!getMaintenanceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, maintenance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAGVreportReplyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aGVreportReply_);
    }
    if (!getStockBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stock_);
    }
    if (!getPerformanceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, performance_);
    }
    if (!getMaintenanceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, maintenance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse)) {
      return super.equals(obj);
    }
    ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse other = (ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse) obj;

    boolean result = true;
    result = result && getAGVreportReply()
        .equals(other.getAGVreportReply());
    result = result && getStock()
        .equals(other.getStock());
    result = result && getPerformance()
        .equals(other.getPerformance());
    result = result && getMaintenance()
        .equals(other.getMaintenance());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGVREPORTREPLY_FIELD_NUMBER;
    hash = (53 * hash) + getAGVreportReply().hashCode();
    hash = (37 * hash) + STOCK_FIELD_NUMBER;
    hash = (53 * hash) + getStock().hashCode();
    hash = (37 * hash) + PERFORMANCE_FIELD_NUMBER;
    hash = (53 * hash) + getPerformance().hashCode();
    hash = (37 * hash) + MAINTENANCE_FIELD_NUMBER;
    hash = (53 * hash) + getMaintenance().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AGVProductivityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AGVProductivityResponse)
      ds.smartwarehouse.project.AGVSystem.AGVProductivityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVProductivityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVProductivityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.class, ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.Builder.class);
    }

    // Construct using ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aGVreportReply_ = "";

      stock_ = "";

      performance_ = "";

      maintenance_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_AGVProductivityResponse_descriptor;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse getDefaultInstanceForType() {
      return ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse build() {
      ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse buildPartial() {
      ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse result = new ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse(this);
      result.aGVreportReply_ = aGVreportReply_;
      result.stock_ = stock_;
      result.performance_ = performance_;
      result.maintenance_ = maintenance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse) {
        return mergeFrom((ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse other) {
      if (other == ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse.getDefaultInstance()) return this;
      if (!other.getAGVreportReply().isEmpty()) {
        aGVreportReply_ = other.aGVreportReply_;
        onChanged();
      }
      if (!other.getStock().isEmpty()) {
        stock_ = other.stock_;
        onChanged();
      }
      if (!other.getPerformance().isEmpty()) {
        performance_ = other.performance_;
        onChanged();
      }
      if (!other.getMaintenance().isEmpty()) {
        maintenance_ = other.maintenance_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aGVreportReply_ = "";
    /**
     * <pre>
     *Report Response
     * </pre>
     *
     * <code>string AGVreportReply = 1;</code>
     */
    public java.lang.String getAGVreportReply() {
      java.lang.Object ref = aGVreportReply_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aGVreportReply_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Report Response
     * </pre>
     *
     * <code>string AGVreportReply = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAGVreportReplyBytes() {
      java.lang.Object ref = aGVreportReply_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aGVreportReply_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Report Response
     * </pre>
     *
     * <code>string AGVreportReply = 1;</code>
     */
    public Builder setAGVreportReply(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aGVreportReply_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Report Response
     * </pre>
     *
     * <code>string AGVreportReply = 1;</code>
     */
    public Builder clearAGVreportReply() {
      
      aGVreportReply_ = getDefaultInstance().getAGVreportReply();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Report Response
     * </pre>
     *
     * <code>string AGVreportReply = 1;</code>
     */
    public Builder setAGVreportReplyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aGVreportReply_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stock_ = "";
    /**
     * <pre>
     *stock track
     * </pre>
     *
     * <code>string stock = 2;</code>
     */
    public java.lang.String getStock() {
      java.lang.Object ref = stock_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stock_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *stock track
     * </pre>
     *
     * <code>string stock = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStockBytes() {
      java.lang.Object ref = stock_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stock_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *stock track
     * </pre>
     *
     * <code>string stock = 2;</code>
     */
    public Builder setStock(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stock_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *stock track
     * </pre>
     *
     * <code>string stock = 2;</code>
     */
    public Builder clearStock() {
      
      stock_ = getDefaultInstance().getStock();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *stock track
     * </pre>
     *
     * <code>string stock = 2;</code>
     */
    public Builder setStockBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stock_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object performance_ = "";
    /**
     * <pre>
     *performance of AGVs
     * </pre>
     *
     * <code>string performance = 3;</code>
     */
    public java.lang.String getPerformance() {
      java.lang.Object ref = performance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        performance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *performance of AGVs
     * </pre>
     *
     * <code>string performance = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPerformanceBytes() {
      java.lang.Object ref = performance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *performance of AGVs
     * </pre>
     *
     * <code>string performance = 3;</code>
     */
    public Builder setPerformance(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      performance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *performance of AGVs
     * </pre>
     *
     * <code>string performance = 3;</code>
     */
    public Builder clearPerformance() {
      
      performance_ = getDefaultInstance().getPerformance();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *performance of AGVs
     * </pre>
     *
     * <code>string performance = 3;</code>
     */
    public Builder setPerformanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      performance_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object maintenance_ = "";
    /**
     * <pre>
     *maintenance of AGVs
     * </pre>
     *
     * <code>string maintenance = 4;</code>
     */
    public java.lang.String getMaintenance() {
      java.lang.Object ref = maintenance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maintenance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *maintenance of AGVs
     * </pre>
     *
     * <code>string maintenance = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMaintenanceBytes() {
      java.lang.Object ref = maintenance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maintenance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *maintenance of AGVs
     * </pre>
     *
     * <code>string maintenance = 4;</code>
     */
    public Builder setMaintenance(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      maintenance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *maintenance of AGVs
     * </pre>
     *
     * <code>string maintenance = 4;</code>
     */
    public Builder clearMaintenance() {
      
      maintenance_ = getDefaultInstance().getMaintenance();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *maintenance of AGVs
     * </pre>
     *
     * <code>string maintenance = 4;</code>
     */
    public Builder setMaintenanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      maintenance_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AGVProductivityResponse)
  }

  // @@protoc_insertion_point(class_scope:AGVProductivityResponse)
  private static final ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse();
  }

  public static ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AGVProductivityResponse>
      PARSER = new com.google.protobuf.AbstractParser<AGVProductivityResponse>() {
    @java.lang.Override
    public AGVProductivityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AGVProductivityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AGVProductivityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AGVProductivityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartwarehouse.project.AGVSystem.AGVProductivityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

