// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface AGVProductivityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AGVProductivityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVreportReply = 1;</code>
   */
  java.lang.String getAGVreportReply();
  /**
   * <code>string AGVreportReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVreportReplyBytes();
}
