// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface AGVProductivityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AGVProductivityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Report Response
   * </pre>
   *
   * <code>string AGVreportReply = 1;</code>
   */
  java.lang.String getAGVreportReply();
  /**
   * <pre>
   *Report Response
   * </pre>
   *
   * <code>string AGVreportReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVreportReplyBytes();

  /**
   * <pre>
   *stock track
   * </pre>
   *
   * <code>string stock = 2;</code>
   */
  java.lang.String getStock();
  /**
   * <pre>
   *stock track
   * </pre>
   *
   * <code>string stock = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockBytes();

  /**
   * <pre>
   *performance of AGVs
   * </pre>
   *
   * <code>string performance = 3;</code>
   */
  java.lang.String getPerformance();
  /**
   * <pre>
   *performance of AGVs
   * </pre>
   *
   * <code>string performance = 3;</code>
   */
  com.google.protobuf.ByteString
      getPerformanceBytes();

  /**
   * <pre>
   *maintenance of AGVs
   * </pre>
   *
   * <code>string maintenance = 4;</code>
   */
  java.lang.String getMaintenance();
  /**
   * <pre>
   *maintenance of AGVs
   * </pre>
   *
   * <code>string maintenance = 4;</code>
   */
  com.google.protobuf.ByteString
      getMaintenanceBytes();
}
