// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface AGVProductivityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AGVProductivityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVreport = 1;</code>
   */
  java.lang.String getAGVreport();
  /**
   * <code>string AGVreport = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVreportBytes();
}
