// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

/**
 * Protobuf type {@code VehicleTrackingResponse}
 */
public  final class VehicleTrackingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VehicleTrackingResponse)
    VehicleTrackingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VehicleTrackingResponse.newBuilder() to construct.
  private VehicleTrackingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  VehicleTrackingResponse() {
    aGVtype_ = "";
    aGVlocation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VehicleTrackingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aGVtype_ = s;
            break;
          }
          case 16: {

            aGVlocation_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_VehicleTrackingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_VehicleTrackingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.class, ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.Builder.class);
  }

  public static final int AGVTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object aGVtype_;
  /**
   * <code>string AGVtype = 1;</code>
   */
  public java.lang.String getAGVtype() {
    java.lang.Object ref = aGVtype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aGVtype_ = s;
      return s;
    }
  }
  /**
   * <code>string AGVtype = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAGVtypeBytes() {
    java.lang.Object ref = aGVtype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aGVtype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGVLOCATION_FIELD_NUMBER = 2;
  private int aGVlocation_;
  /**
   * <code>int32 AGVlocation = 2;</code>
   */
  public int getAGVlocation() {
    return aGVlocation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAGVtypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aGVtype_);
    }
    if (aGVlocation_ != 0) {
      output.writeInt32(2, aGVlocation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAGVtypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aGVtype_);
    }
    if (aGVlocation_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, aGVlocation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse)) {
      return super.equals(obj);
    }
    ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse other = (ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse) obj;

    boolean result = true;
    result = result && getAGVtype()
        .equals(other.getAGVtype());
    result = result && (getAGVlocation()
        == other.getAGVlocation());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGVTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAGVtype().hashCode();
    hash = (37 * hash) + AGVLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getAGVlocation();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VehicleTrackingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VehicleTrackingResponse)
      ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_VehicleTrackingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_VehicleTrackingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.class, ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.Builder.class);
    }

    // Construct using ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aGVtype_ = "";

      aGVlocation_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartwarehouse.project.AGVSystem.NewAGVSystemImpl.internal_static_VehicleTrackingResponse_descriptor;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse getDefaultInstanceForType() {
      return ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse build() {
      ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse buildPartial() {
      ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse result = new ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse(this);
      result.aGVtype_ = aGVtype_;
      result.aGVlocation_ = aGVlocation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse) {
        return mergeFrom((ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse other) {
      if (other == ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse.getDefaultInstance()) return this;
      if (!other.getAGVtype().isEmpty()) {
        aGVtype_ = other.aGVtype_;
        onChanged();
      }
      if (other.getAGVlocation() != 0) {
        setAGVlocation(other.getAGVlocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aGVtype_ = "";
    /**
     * <code>string AGVtype = 1;</code>
     */
    public java.lang.String getAGVtype() {
      java.lang.Object ref = aGVtype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aGVtype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string AGVtype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAGVtypeBytes() {
      java.lang.Object ref = aGVtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aGVtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AGVtype = 1;</code>
     */
    public Builder setAGVtype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aGVtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AGVtype = 1;</code>
     */
    public Builder clearAGVtype() {
      
      aGVtype_ = getDefaultInstance().getAGVtype();
      onChanged();
      return this;
    }
    /**
     * <code>string AGVtype = 1;</code>
     */
    public Builder setAGVtypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aGVtype_ = value;
      onChanged();
      return this;
    }

    private int aGVlocation_ ;
    /**
     * <code>int32 AGVlocation = 2;</code>
     */
    public int getAGVlocation() {
      return aGVlocation_;
    }
    /**
     * <code>int32 AGVlocation = 2;</code>
     */
    public Builder setAGVlocation(int value) {
      
      aGVlocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AGVlocation = 2;</code>
     */
    public Builder clearAGVlocation() {
      
      aGVlocation_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VehicleTrackingResponse)
  }

  // @@protoc_insertion_point(class_scope:VehicleTrackingResponse)
  private static final ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse();
  }

  public static ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VehicleTrackingResponse>
      PARSER = new com.google.protobuf.AbstractParser<VehicleTrackingResponse>() {
    @java.lang.Override
    public VehicleTrackingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VehicleTrackingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VehicleTrackingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VehicleTrackingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartwarehouse.project.AGVSystem.VehicleTrackingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

