// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface VehicleTrackingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VehicleTrackingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVtype = 1;</code>
   */
  java.lang.String getAGVtype();
  /**
   * <code>string AGVtype = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVtypeBytes();

  /**
   * <code>double AGVlatitude = 2;</code>
   */
  double getAGVlatitude();

  /**
   * <code>double AGVlongitude = 3;</code>
   */
  double getAGVlongitude();
}
