// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AGVSystem.proto

package ds.smartwarehouse.project.AGVSystem;

public interface VehicleTrackingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VehicleTrackingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AGVtype = 1;</code>
   */
  java.lang.String getAGVtype();
  /**
   * <code>string AGVtype = 1;</code>
   */
  com.google.protobuf.ByteString
      getAGVtypeBytes();
}
