// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public final class NewWarehouseManagementImpl {
  private NewWarehouseManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductivityReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductivityReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductivityReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductivityReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemandForecastRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemandForecastRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemandForecastResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemandForecastResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimeOverviewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimeOverviewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimeOverviewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimeOverviewResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031warehouseManagement.proto\"{\n\031Productiv" +
      "ityReportRequest\022\022\n\nprodReport\030\001 \001(\t\022\021\n\t" +
      "Q1earning\030\002 \001(\001\022\021\n\tQ2earning\030\003 \001(\001\022\021\n\tQ3" +
      "earning\030\004 \001(\001\022\021\n\tQ4earning\030\005 \001(\001\"\364\001\n\032Pro" +
      "ductivityReportResponse\022\031\n\021prodReportSer" +
      "vice\030\001 \001(\t\022\026\n\016AGVperformance\030\002 \001(\005\022\025\n\rEm" +
      "ployeeCount\030\003 \001(\005\022\021\n\tQ1earning\030\004 \001(\001\022\021\n\t" +
      "Q2earning\030\005 \001(\001\022\021\n\tQ3earning\030\006 \001(\001\022\021\n\tQ4" +
      "earning\030\007 \001(\001\022\020\n\010QuartAvg\030\010 \001(\001\022\030\n\020Annua" +
      "lAvgEarning\030\t \001(\001\022\024\n\014totalEarning\030\n \001(\001\"" +
      "C\n\025DemandForecastRequest\022\027\n\017forecastMess" +
      "age\030\001 \001(\t\022\021\n\titemsSold\030\002 \001(\005\"D\n\026DemandFo" +
      "recastResponse\022\026\n\016forecastReview\030\001 \001(\t\022\022" +
      "\n\nhighDemand\030\002 \001(\005\"2\n\027RealTimeOverviewRe" +
      "quest\022\027\n\017overviewMessage\030\001 \001(\t\"N\n\030RealTi" +
      "meOverviewResponse\022\027\n\017vehicleOverview\030\001 " +
      "\001(\t\022\031\n\021warehouseOverview\030\002 \001(\t2\373\001\n\022Wareh" +
      "ouseManagment\022O\n\022productivityReport\022\032.Pr" +
      "oductivityReportRequest\032\033.ProductivityRe" +
      "portResponse\"\000\022E\n\016demandForecast\022\026.Deman" +
      "dForecastRequest\032\027.DemandForecastRespons" +
      "e\"\000(\001\022M\n\020realTimeOverview\022\030.RealTimeOver" +
      "viewRequest\032\031.RealTimeOverviewResponse\"\000" +
      "(\0010\001BM\n-ds.smartwarehouse.project.wareho" +
      "useManagementB\032NewWarehouseManagementImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProductivityReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductivityReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductivityReportRequest_descriptor,
        new java.lang.String[] { "ProdReport", "Q1Earning", "Q2Earning", "Q3Earning", "Q4Earning", });
    internal_static_ProductivityReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductivityReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductivityReportResponse_descriptor,
        new java.lang.String[] { "ProdReportService", "AGVperformance", "EmployeeCount", "Q1Earning", "Q2Earning", "Q3Earning", "Q4Earning", "QuartAvg", "AnnualAvgEarning", "TotalEarning", });
    internal_static_DemandForecastRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DemandForecastRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemandForecastRequest_descriptor,
        new java.lang.String[] { "ForecastMessage", "ItemsSold", });
    internal_static_DemandForecastResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DemandForecastResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemandForecastResponse_descriptor,
        new java.lang.String[] { "ForecastReview", "HighDemand", });
    internal_static_RealTimeOverviewRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RealTimeOverviewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimeOverviewRequest_descriptor,
        new java.lang.String[] { "OverviewMessage", });
    internal_static_RealTimeOverviewResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RealTimeOverviewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimeOverviewResponse_descriptor,
        new java.lang.String[] { "VehicleOverview", "WarehouseOverview", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
