// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public final class NewWarehouseManagementImpl {
  private NewWarehouseManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductivityReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductivityReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductivityReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductivityReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemandForecastRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemandForecastRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemandForecastResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemandForecastResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimeOverviewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimeOverviewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RealTimeOverviewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RealTimeOverviewResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031warehouseManagement.proto\"/\n\031Productiv" +
      "ityReportRequest\022\022\n\nprodReport\030\001 \001(\t\"7\n\032" +
      "ProductivityReportResponse\022\031\n\021prodReport" +
      "Service\030\001 \001(\t\"0\n\025DemandForecastRequest\022\027" +
      "\n\017forecastMessage\030\001 \001(\t\"D\n\026DemandForecas" +
      "tResponse\022\026\n\016forecastReview\030\001 \001(\t\022\022\n\nhig" +
      "hDemand\030\002 \001(\005\"2\n\027RealTimeOverviewRequest" +
      "\022\027\n\017overviewMessage\030\001 \001(\t\"N\n\030RealTimeOve" +
      "rviewResponse\022\027\n\017vehicleOverview\030\001 \001(\t\022\031" +
      "\n\021warehouseOverview\030\002 \001(\t2\373\001\n\022WarehouseM" +
      "anagment\022O\n\022productivityReport\022\032.Product" +
      "ivityReportRequest\032\033.ProductivityReportR" +
      "esponse\"\000\022E\n\016demandForecast\022\026.DemandFore" +
      "castRequest\032\027.DemandForecastResponse\"\000(\001" +
      "\022M\n\020realTimeOverview\022\030.RealTimeOverviewR" +
      "equest\032\031.RealTimeOverviewResponse\"\000(\0010\001B" +
      "M\n-ds.smartwarehouse.project.warehouseMa" +
      "nagementB\032NewWarehouseManagementImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProductivityReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductivityReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductivityReportRequest_descriptor,
        new java.lang.String[] { "ProdReport", });
    internal_static_ProductivityReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductivityReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductivityReportResponse_descriptor,
        new java.lang.String[] { "ProdReportService", });
    internal_static_DemandForecastRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DemandForecastRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemandForecastRequest_descriptor,
        new java.lang.String[] { "ForecastMessage", });
    internal_static_DemandForecastResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DemandForecastResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemandForecastResponse_descriptor,
        new java.lang.String[] { "ForecastReview", "HighDemand", });
    internal_static_RealTimeOverviewRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RealTimeOverviewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimeOverviewRequest_descriptor,
        new java.lang.String[] { "OverviewMessage", });
    internal_static_RealTimeOverviewResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RealTimeOverviewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RealTimeOverviewResponse_descriptor,
        new java.lang.String[] { "VehicleOverview", "WarehouseOverview", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
