// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public interface ProductivityReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductivityReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prodReportService = 1;</code>
   */
  java.lang.String getProdReportService();
  /**
   * <code>string prodReportService = 1;</code>
   */
  com.google.protobuf.ByteString
      getProdReportServiceBytes();
}
