// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public interface ProductivityReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductivityReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prodReport = 1;</code>
   */
  java.lang.String getProdReport();
  /**
   * <code>string prodReport = 1;</code>
   */
  com.google.protobuf.ByteString
      getProdReportBytes();
}
