// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public interface RealTimeOverviewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimeOverviewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *overview of warehouse operations request
   * </pre>
   *
   * <code>string overviewMessage = 1;</code>
   */
  java.lang.String getOverviewMessage();
  /**
   * <pre>
   *overview of warehouse operations request
   * </pre>
   *
   * <code>string overviewMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getOverviewMessageBytes();
}
