// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

/**
 * Protobuf type {@code RealTimeOverviewResponse}
 */
public  final class RealTimeOverviewResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RealTimeOverviewResponse)
    RealTimeOverviewResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RealTimeOverviewResponse.newBuilder() to construct.
  private RealTimeOverviewResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RealTimeOverviewResponse() {
    vehicleOverview_ = "";
    warehouseOverview_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RealTimeOverviewResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            vehicleOverview_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            warehouseOverview_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartwarehouse.project.warehouseManagement.NewWarehouseManagementImpl.internal_static_RealTimeOverviewResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartwarehouse.project.warehouseManagement.NewWarehouseManagementImpl.internal_static_RealTimeOverviewResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.class, ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.Builder.class);
  }

  public static final int VEHICLEOVERVIEW_FIELD_NUMBER = 1;
  private volatile java.lang.Object vehicleOverview_;
  /**
   * <code>string vehicleOverview = 1;</code>
   */
  public java.lang.String getVehicleOverview() {
    java.lang.Object ref = vehicleOverview_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicleOverview_ = s;
      return s;
    }
  }
  /**
   * <code>string vehicleOverview = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVehicleOverviewBytes() {
    java.lang.Object ref = vehicleOverview_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehicleOverview_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WAREHOUSEOVERVIEW_FIELD_NUMBER = 2;
  private volatile java.lang.Object warehouseOverview_;
  /**
   * <code>string warehouseOverview = 2;</code>
   */
  public java.lang.String getWarehouseOverview() {
    java.lang.Object ref = warehouseOverview_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      warehouseOverview_ = s;
      return s;
    }
  }
  /**
   * <code>string warehouseOverview = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWarehouseOverviewBytes() {
    java.lang.Object ref = warehouseOverview_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      warehouseOverview_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVehicleOverviewBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vehicleOverview_);
    }
    if (!getWarehouseOverviewBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, warehouseOverview_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVehicleOverviewBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vehicleOverview_);
    }
    if (!getWarehouseOverviewBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, warehouseOverview_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse)) {
      return super.equals(obj);
    }
    ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse other = (ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse) obj;

    boolean result = true;
    result = result && getVehicleOverview()
        .equals(other.getVehicleOverview());
    result = result && getWarehouseOverview()
        .equals(other.getWarehouseOverview());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VEHICLEOVERVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleOverview().hashCode();
    hash = (37 * hash) + WAREHOUSEOVERVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getWarehouseOverview().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RealTimeOverviewResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RealTimeOverviewResponse)
      ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartwarehouse.project.warehouseManagement.NewWarehouseManagementImpl.internal_static_RealTimeOverviewResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartwarehouse.project.warehouseManagement.NewWarehouseManagementImpl.internal_static_RealTimeOverviewResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.class, ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.Builder.class);
    }

    // Construct using ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vehicleOverview_ = "";

      warehouseOverview_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartwarehouse.project.warehouseManagement.NewWarehouseManagementImpl.internal_static_RealTimeOverviewResponse_descriptor;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse getDefaultInstanceForType() {
      return ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse build() {
      ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse buildPartial() {
      ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse result = new ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse(this);
      result.vehicleOverview_ = vehicleOverview_;
      result.warehouseOverview_ = warehouseOverview_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse) {
        return mergeFrom((ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse other) {
      if (other == ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse.getDefaultInstance()) return this;
      if (!other.getVehicleOverview().isEmpty()) {
        vehicleOverview_ = other.vehicleOverview_;
        onChanged();
      }
      if (!other.getWarehouseOverview().isEmpty()) {
        warehouseOverview_ = other.warehouseOverview_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object vehicleOverview_ = "";
    /**
     * <code>string vehicleOverview = 1;</code>
     */
    public java.lang.String getVehicleOverview() {
      java.lang.Object ref = vehicleOverview_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleOverview_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vehicleOverview = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVehicleOverviewBytes() {
      java.lang.Object ref = vehicleOverview_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleOverview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vehicleOverview = 1;</code>
     */
    public Builder setVehicleOverview(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehicleOverview_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vehicleOverview = 1;</code>
     */
    public Builder clearVehicleOverview() {
      
      vehicleOverview_ = getDefaultInstance().getVehicleOverview();
      onChanged();
      return this;
    }
    /**
     * <code>string vehicleOverview = 1;</code>
     */
    public Builder setVehicleOverviewBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehicleOverview_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object warehouseOverview_ = "";
    /**
     * <code>string warehouseOverview = 2;</code>
     */
    public java.lang.String getWarehouseOverview() {
      java.lang.Object ref = warehouseOverview_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warehouseOverview_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string warehouseOverview = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWarehouseOverviewBytes() {
      java.lang.Object ref = warehouseOverview_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warehouseOverview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string warehouseOverview = 2;</code>
     */
    public Builder setWarehouseOverview(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      warehouseOverview_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string warehouseOverview = 2;</code>
     */
    public Builder clearWarehouseOverview() {
      
      warehouseOverview_ = getDefaultInstance().getWarehouseOverview();
      onChanged();
      return this;
    }
    /**
     * <code>string warehouseOverview = 2;</code>
     */
    public Builder setWarehouseOverviewBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      warehouseOverview_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RealTimeOverviewResponse)
  }

  // @@protoc_insertion_point(class_scope:RealTimeOverviewResponse)
  private static final ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse();
  }

  public static ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RealTimeOverviewResponse>
      PARSER = new com.google.protobuf.AbstractParser<RealTimeOverviewResponse>() {
    @java.lang.Override
    public RealTimeOverviewResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RealTimeOverviewResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RealTimeOverviewResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RealTimeOverviewResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartwarehouse.project.warehouseManagement.RealTimeOverviewResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

