// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouseManagement.proto

package ds.smartwarehouse.project.warehouseManagement;

public interface RealTimeOverviewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealTimeOverviewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vehicleOverview = 1;</code>
   */
  java.lang.String getVehicleOverview();
  /**
   * <code>string vehicleOverview = 1;</code>
   */
  com.google.protobuf.ByteString
      getVehicleOverviewBytes();

  /**
   * <code>string warehouseOverview = 2;</code>
   */
  java.lang.String getWarehouseOverview();
  /**
   * <code>string warehouseOverview = 2;</code>
   */
  com.google.protobuf.ByteString
      getWarehouseOverviewBytes();
}
