// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public final class NewOrderManagementImpl {
  private NewOrderManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockReplenishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockReplenishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockReplenishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockReplenishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderTrackingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderTrackingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderTrackingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderTrackingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025orderManagement.proto\"$\n\014StockRequest\022" +
      "\024\n\014stockMessage\030\001 \001(\t\"L\n\rStockResponse\022\023" +
      "\n\013stockNumber\030\001 \001(\005\022\021\n\tstockType\030\002 \001(\t\022\023" +
      "\n\013notFoundMsg\030\003 \001(\t\"1\n\025StockReplenishReq" +
      "uest\022\030\n\020replenishMessage\030\001 \001(\t\"n\n\026StockR" +
      "eplenishResponse\022\025\n\rreplenishType\030\001 \001(\t\022" +
      "\020\n\010lowStock\030\002 \001(\005\022\021\n\thighStock\030\003 \001(\005\022\030\n\020" +
      "stockReplenished\030\004 \001(\010\"+\n\024OrderTrackingR" +
      "equest\022\023\n\013orderNumber\030\001 \001(\005\"A\n\025OrderTrac" +
      "kingResponse\022\023\n\013orderNumber\030\001 \001(\005\022\023\n\013ord" +
      "erStatus\030\002 \001(\t2\313\001\n\017OrderManagement\022-\n\nst" +
      "ockCheck\022\r.StockRequest\032\016.StockResponse\"" +
      "\000\022E\n\016replenishStock\022\026.StockReplenishRequ" +
      "est\032\027.StockReplenishResponse\"\0000\001\022B\n\rorde" +
      "rTracking\022\025.OrderTrackingRequest\032\026.Order" +
      "TrackingResponse\"\000(\001BE\n)ds.smartwarehous" +
      "e.project.orderManagementB\026NewOrderManag" +
      "ementImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "StockMessage", });
    internal_static_StockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockResponse_descriptor,
        new java.lang.String[] { "StockNumber", "StockType", "NotFoundMsg", });
    internal_static_StockReplenishRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockReplenishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockReplenishRequest_descriptor,
        new java.lang.String[] { "ReplenishMessage", });
    internal_static_StockReplenishResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StockReplenishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockReplenishResponse_descriptor,
        new java.lang.String[] { "ReplenishType", "LowStock", "HighStock", "StockReplenished", });
    internal_static_OrderTrackingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderTrackingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderTrackingRequest_descriptor,
        new java.lang.String[] { "OrderNumber", });
    internal_static_OrderTrackingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderTrackingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderTrackingResponse_descriptor,
        new java.lang.String[] { "OrderNumber", "OrderStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
