// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public interface OrderTrackingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderTrackingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNumber = 1;</code>
   */
  int getOrderNumber();
}
