// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public interface OrderTrackingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderTrackingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNumber = 1;</code>
   */
  int getOrderNumber();

  /**
   * <code>string orderStatus = 2;</code>
   */
  java.lang.String getOrderStatus();
  /**
   * <code>string orderStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderStatusBytes();
}
