// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

/**
 * Protobuf type {@code StockReplenishResponse}
 */
public  final class StockReplenishResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StockReplenishResponse)
    StockReplenishResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockReplenishResponse.newBuilder() to construct.
  private StockReplenishResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockReplenishResponse() {
    replenishType_ = "";
    lowStock_ = 0;
    highStock_ = 0;
    stockReplenished_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StockReplenishResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            replenishType_ = s;
            break;
          }
          case 16: {

            lowStock_ = input.readInt32();
            break;
          }
          case 24: {

            highStock_ = input.readInt32();
            break;
          }
          case 32: {

            stockReplenished_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.smartwarehouse.project.orderManagement.NewOrderManagementImpl.internal_static_StockReplenishResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.smartwarehouse.project.orderManagement.NewOrderManagementImpl.internal_static_StockReplenishResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.smartwarehouse.project.orderManagement.StockReplenishResponse.class, ds.smartwarehouse.project.orderManagement.StockReplenishResponse.Builder.class);
  }

  public static final int REPLENISHTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object replenishType_;
  /**
   * <pre>
   *type of stock needed
   * </pre>
   *
   * <code>string replenishType = 1;</code>
   */
  public java.lang.String getReplenishType() {
    java.lang.Object ref = replenishType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      replenishType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *type of stock needed
   * </pre>
   *
   * <code>string replenishType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReplenishTypeBytes() {
    java.lang.Object ref = replenishType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      replenishType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOWSTOCK_FIELD_NUMBER = 2;
  private int lowStock_;
  /**
   * <pre>
   *low stock if required
   * </pre>
   *
   * <code>int32 lowStock = 2;</code>
   */
  public int getLowStock() {
    return lowStock_;
  }

  public static final int HIGHSTOCK_FIELD_NUMBER = 3;
  private int highStock_;
  /**
   * <pre>
   *check if stock is high or in high demand
   * </pre>
   *
   * <code>int32 highStock = 3;</code>
   */
  public int getHighStock() {
    return highStock_;
  }

  public static final int STOCKREPLENISHED_FIELD_NUMBER = 4;
  private boolean stockReplenished_;
  /**
   * <pre>
   *boolean value to decide if stock needs replenishing
   * </pre>
   *
   * <code>bool stockReplenished = 4;</code>
   */
  public boolean getStockReplenished() {
    return stockReplenished_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReplenishTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replenishType_);
    }
    if (lowStock_ != 0) {
      output.writeInt32(2, lowStock_);
    }
    if (highStock_ != 0) {
      output.writeInt32(3, highStock_);
    }
    if (stockReplenished_ != false) {
      output.writeBool(4, stockReplenished_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReplenishTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replenishType_);
    }
    if (lowStock_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, lowStock_);
    }
    if (highStock_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, highStock_);
    }
    if (stockReplenished_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, stockReplenished_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.smartwarehouse.project.orderManagement.StockReplenishResponse)) {
      return super.equals(obj);
    }
    ds.smartwarehouse.project.orderManagement.StockReplenishResponse other = (ds.smartwarehouse.project.orderManagement.StockReplenishResponse) obj;

    boolean result = true;
    result = result && getReplenishType()
        .equals(other.getReplenishType());
    result = result && (getLowStock()
        == other.getLowStock());
    result = result && (getHighStock()
        == other.getHighStock());
    result = result && (getStockReplenished()
        == other.getStockReplenished());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLENISHTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getReplenishType().hashCode();
    hash = (37 * hash) + LOWSTOCK_FIELD_NUMBER;
    hash = (53 * hash) + getLowStock();
    hash = (37 * hash) + HIGHSTOCK_FIELD_NUMBER;
    hash = (53 * hash) + getHighStock();
    hash = (37 * hash) + STOCKREPLENISHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStockReplenished());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.smartwarehouse.project.orderManagement.StockReplenishResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StockReplenishResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StockReplenishResponse)
      ds.smartwarehouse.project.orderManagement.StockReplenishResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.smartwarehouse.project.orderManagement.NewOrderManagementImpl.internal_static_StockReplenishResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.smartwarehouse.project.orderManagement.NewOrderManagementImpl.internal_static_StockReplenishResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.smartwarehouse.project.orderManagement.StockReplenishResponse.class, ds.smartwarehouse.project.orderManagement.StockReplenishResponse.Builder.class);
    }

    // Construct using ds.smartwarehouse.project.orderManagement.StockReplenishResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      replenishType_ = "";

      lowStock_ = 0;

      highStock_ = 0;

      stockReplenished_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.smartwarehouse.project.orderManagement.NewOrderManagementImpl.internal_static_StockReplenishResponse_descriptor;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.orderManagement.StockReplenishResponse getDefaultInstanceForType() {
      return ds.smartwarehouse.project.orderManagement.StockReplenishResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.smartwarehouse.project.orderManagement.StockReplenishResponse build() {
      ds.smartwarehouse.project.orderManagement.StockReplenishResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.smartwarehouse.project.orderManagement.StockReplenishResponse buildPartial() {
      ds.smartwarehouse.project.orderManagement.StockReplenishResponse result = new ds.smartwarehouse.project.orderManagement.StockReplenishResponse(this);
      result.replenishType_ = replenishType_;
      result.lowStock_ = lowStock_;
      result.highStock_ = highStock_;
      result.stockReplenished_ = stockReplenished_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.smartwarehouse.project.orderManagement.StockReplenishResponse) {
        return mergeFrom((ds.smartwarehouse.project.orderManagement.StockReplenishResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.smartwarehouse.project.orderManagement.StockReplenishResponse other) {
      if (other == ds.smartwarehouse.project.orderManagement.StockReplenishResponse.getDefaultInstance()) return this;
      if (!other.getReplenishType().isEmpty()) {
        replenishType_ = other.replenishType_;
        onChanged();
      }
      if (other.getLowStock() != 0) {
        setLowStock(other.getLowStock());
      }
      if (other.getHighStock() != 0) {
        setHighStock(other.getHighStock());
      }
      if (other.getStockReplenished() != false) {
        setStockReplenished(other.getStockReplenished());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.smartwarehouse.project.orderManagement.StockReplenishResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.smartwarehouse.project.orderManagement.StockReplenishResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object replenishType_ = "";
    /**
     * <pre>
     *type of stock needed
     * </pre>
     *
     * <code>string replenishType = 1;</code>
     */
    public java.lang.String getReplenishType() {
      java.lang.Object ref = replenishType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replenishType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *type of stock needed
     * </pre>
     *
     * <code>string replenishType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplenishTypeBytes() {
      java.lang.Object ref = replenishType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replenishType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *type of stock needed
     * </pre>
     *
     * <code>string replenishType = 1;</code>
     */
    public Builder setReplenishType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      replenishType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *type of stock needed
     * </pre>
     *
     * <code>string replenishType = 1;</code>
     */
    public Builder clearReplenishType() {
      
      replenishType_ = getDefaultInstance().getReplenishType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *type of stock needed
     * </pre>
     *
     * <code>string replenishType = 1;</code>
     */
    public Builder setReplenishTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      replenishType_ = value;
      onChanged();
      return this;
    }

    private int lowStock_ ;
    /**
     * <pre>
     *low stock if required
     * </pre>
     *
     * <code>int32 lowStock = 2;</code>
     */
    public int getLowStock() {
      return lowStock_;
    }
    /**
     * <pre>
     *low stock if required
     * </pre>
     *
     * <code>int32 lowStock = 2;</code>
     */
    public Builder setLowStock(int value) {
      
      lowStock_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *low stock if required
     * </pre>
     *
     * <code>int32 lowStock = 2;</code>
     */
    public Builder clearLowStock() {
      
      lowStock_ = 0;
      onChanged();
      return this;
    }

    private int highStock_ ;
    /**
     * <pre>
     *check if stock is high or in high demand
     * </pre>
     *
     * <code>int32 highStock = 3;</code>
     */
    public int getHighStock() {
      return highStock_;
    }
    /**
     * <pre>
     *check if stock is high or in high demand
     * </pre>
     *
     * <code>int32 highStock = 3;</code>
     */
    public Builder setHighStock(int value) {
      
      highStock_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *check if stock is high or in high demand
     * </pre>
     *
     * <code>int32 highStock = 3;</code>
     */
    public Builder clearHighStock() {
      
      highStock_ = 0;
      onChanged();
      return this;
    }

    private boolean stockReplenished_ ;
    /**
     * <pre>
     *boolean value to decide if stock needs replenishing
     * </pre>
     *
     * <code>bool stockReplenished = 4;</code>
     */
    public boolean getStockReplenished() {
      return stockReplenished_;
    }
    /**
     * <pre>
     *boolean value to decide if stock needs replenishing
     * </pre>
     *
     * <code>bool stockReplenished = 4;</code>
     */
    public Builder setStockReplenished(boolean value) {
      
      stockReplenished_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *boolean value to decide if stock needs replenishing
     * </pre>
     *
     * <code>bool stockReplenished = 4;</code>
     */
    public Builder clearStockReplenished() {
      
      stockReplenished_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StockReplenishResponse)
  }

  // @@protoc_insertion_point(class_scope:StockReplenishResponse)
  private static final ds.smartwarehouse.project.orderManagement.StockReplenishResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.smartwarehouse.project.orderManagement.StockReplenishResponse();
  }

  public static ds.smartwarehouse.project.orderManagement.StockReplenishResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockReplenishResponse>
      PARSER = new com.google.protobuf.AbstractParser<StockReplenishResponse>() {
    @java.lang.Override
    public StockReplenishResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StockReplenishResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StockReplenishResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockReplenishResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.smartwarehouse.project.orderManagement.StockReplenishResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

