// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public interface StockReplenishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockReplenishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string replenishMessage = 1;</code>
   */
  java.lang.String getReplenishMessage();
  /**
   * <code>string replenishMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplenishMessageBytes();
}
