// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Stock number
   * </pre>
   *
   * <code>int32 stockNumber = 1;</code>
   */
  int getStockNumber();

  /**
   * <pre>
   *type of stock
   * </pre>
   *
   * <code>string stockType = 2;</code>
   */
  java.lang.String getStockType();
  /**
   * <pre>
   *type of stock
   * </pre>
   *
   * <code>string stockType = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockTypeBytes();

  /**
   * <pre>
   *if item not found error message
   * </pre>
   *
   * <code>string notFoundMsg = 3;</code>
   */
  java.lang.String getNotFoundMsg();
  /**
   * <pre>
   *if item not found error message
   * </pre>
   *
   * <code>string notFoundMsg = 3;</code>
   */
  com.google.protobuf.ByteString
      getNotFoundMsgBytes();
}
