// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package ds.smartwarehouse.project.orderManagement;

public interface StockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Stock request message
   * </pre>
   *
   * <code>string stockMessage = 1;</code>
   */
  java.lang.String getStockMessage();
  /**
   * <pre>
   *Stock request message
   * </pre>
   *
   * <code>string stockMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getStockMessageBytes();
}
